### ISSUE TITLE
Add pagination configuration files

### ISSUE THREAD

**Issue by martinscooper** [label-sleuth/label-sleuth.org#33]
When pagination was added to the frontend panels, new configuration variables has been introduced (more information [here](https://github.com/label-sleuth/label-sleuth/pull/231)). Add this new settings to the [System configuration section of the Webpage](https://www.label-sleuth.org/docs/dev/configuration.html).

**Comment by yannisk2** [comment]
Thanks @martinscooper for creating and resolving the issue! I am closing it now, as is addressed by your PR https://github.com/label-sleuth/label-sleuth.org/pull/34 that was just merged.
