### ISSUE TITLE
Update example response in /import_labels endpoint

### ISSUE THREAD

**Issue by martinscooper** [label-sleuth/label-sleuth.org#9]
The response of `/import_labels` has a `categories` attribute, which is a list of the categories where labels have been added. Each item of the list had two attributes, `category` and `counter`. The `category` attribute has been changed to `category_id` as part of [this commit](https://github.com/label-sleuth/label-sleuth/commit/1592103c119d14e9a0687fff1791df49a3fd5968).

To update the webpage [this line](https://github.com/label-sleuth/label-sleuth.org/blob/7b10ea5fcaf52945a2ee0acd5fc018118336a2a9/docs/docs/dev/api.md?plain=1#L477) should be changed to something like `category_id: "3"`.

**Comment by yannisk2** [comment]
Thanks @martinscooper; I will look into this once the outstanding PR against the API page is merged.

**Comment by yannisk2** [comment]
Closing this issue, as it has been addressed in PR https://github.com/label-sleuth/label-sleuth.org/pull/11.
